<?php
require_once __DIR__.'/core/layout.php'; require_auth(); $pdo=db();
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();
 $productId=(int)post('product_id');$quantity=max(1,(int)post('quantity','1'));$unitPrice=(float)post('unit_price');$customer=post('customer','Kliyan comptoir')?:'Kliyan comptoir';$payment=post('payment','Lajan kach');
 try{$pdo->beginTransaction();$stmt=$pdo->prepare('SELECT id,model,quantite,prix FROM produit WHERE id=? FOR UPDATE');$stmt->execute([$productId]);$product=$stmt->fetch();
  if(!$product)throw new RuntimeException('Pwodwi a pa egziste.');if((int)$product['quantite']<$quantity)throw new RuntimeException('Pa gen ase stock. Gen sèlman '.$product['quantite'].' ki disponib.');if($unitPrice<0)throw new RuntimeException('Pri a pa valab.');
  $total=$quantity*$unitPrice;$pdo->prepare('INSERT INTO sales(customer_name,payment_method,total,created_by) VALUES(?,?,?,?)')->execute([$customer,$payment,$total,current_user()['user_id']]);$saleId=(int)$pdo->lastInsertId();
  $pdo->prepare('INSERT INTO sale_items(sale_id,product_id,quantity,unit_price) VALUES(?,?,?,?)')->execute([$saleId,$productId,$quantity,$unitPrice]);$pdo->prepare('UPDATE produit SET quantite=quantite-? WHERE id=?')->execute([$quantity,$productId]);$pdo->prepare("INSERT INTO stock_movements(product_id,movement_type,quantity,note,created_by) VALUES(?,'out',?,'Vant #$saleId',?)")->execute([$productId,-$quantity,current_user()['user_id']]);$pdo->commit();flash('success','Vant #'.$saleId.' anrejistre. Total: '.money($total));redirect('sales.php');
 }catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();flash('error',$e->getMessage());redirect('sales.php?new=1');}}
$products=$pdo->query('SELECT id,marque,model,referance,prix,quantite FROM produit WHERE quantite>0 ORDER BY marque,model')->fetchAll();$show=isset($_GET['new']);
$sales=$pdo->query('SELECT s.*,u.user_name,u.user_prenom,(SELECT COUNT(*) FROM sale_items i WHERE i.sale_id=s.sale_id) item_count FROM sales s LEFT JOIN users u ON u.user_id=s.created_by ORDER BY s.sale_id DESC LIMIT 100')->fetchAll();page_header($show?'Anrejistre yon vant':'Lavant','sales');
?>
<?php if($show):?><div class="card"><form method="post" class="form-grid"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><div class="field full"><label>Pwodwi *</label><select name="product_id" required autofocus data-product-select><option value="">— Chwazi pwodwi —</option><?php foreach($products as $p):?><option value="<?=(int)$p['id']?>" data-price="<?=e($p['prix'])?>" data-stock="<?=(int)$p['quantite']?>"><?=e(trim($p['marque'].' '.$p['model']))?> · <?=e($p['referance'])?> (<?=(int)$p['quantite']?> disponib)</option><?php endforeach;?></select><small data-stock-help></small></div><div class="field"><label>Kantite *</label><input type="number" name="quantity" min="1" value="1" required></div><div class="field"><label>Pri pou chak *</label><input type="number" name="unit_price" min="0" step="0.01" required></div><div class="field"><label>Non kliyan</label><input name="customer" value="Kliyan comptoir"></div><div class="field"><label>Metòd peman</label><select name="payment"><option>Lajan kach</option><option>Kat</option><option>Transfè</option><option>Kredi</option><option>Lòt</option></select></div><div class="field full help-box">Lè ou sove vant lan, kantite a ap retire otomatikman nan stock.</div><div class="form-footer"><a class="button" href="sales.php">Anile</a><button class="primary">Konfime vant lan</button></div></form></div>
<?php else:?><div class="page-actions"><p class="muted">Tout lavant ou anrejistre nan aplikasyon an.</p><a class="button primary" href="sales.php?new=1">+ Nouvo vant</a></div><div class="card"><div class="table-wrap"><table><thead><tr><th>Nimewo</th><th>Kliyan</th><th>Peman</th><th>Total</th><th>Anrejistre pa</th><th>Dat</th></tr></thead><tbody><?php foreach($sales as $s):?><tr><td><strong>#<?=(int)$s['sale_id']?></strong></td><td><?=e($s['customer_name'])?></td><td><?=e($s['payment_method'])?></td><td><strong><?=e(money($s['total']))?></strong></td><td><?=e(trim(($s['user_name']??'').' '.($s['user_prenom']??'')))?:'—'?></td><td><?=e(date('d/m/Y H:i',strtotime($s['created_at'])))?></td></tr><?php endforeach;?><?php if(!$sales):?><tr><td colspan="6" class="empty">Poko gen lavant.</td></tr><?php endif;?></tbody></table></div></div><?php endif;page_footer();?>
