<?php
require_once __DIR__.'/core/layout.php'; require_auth(); $pdo=db();
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$action=post('action');
 if($action==='save'){ $id=(int)post('id','0');$v=[post('name'),post('contact'),post('address'),post('city'),post('phone')];
  if($v[0]===''){flash('error','Non founisè a obligatwa.');}
  elseif($id){$pdo->prepare('UPDATE fournisseur SET nom=?,prenom=?,adresse=?,ville=?,num_tel=? WHERE fourn_id=?')->execute(array_merge($v,[$id]));log_activity('update','supplier',$id,$v[0]);flash('success','Founisè a modifye.');}
  else{$pdo->prepare('INSERT INTO fournisseur(nom,prenom,adresse,ville,num_tel) VALUES(?,?,?,?,?)')->execute($v);$id=(int)$pdo->lastInsertId();log_activity('create','supplier',$id,$v[0]);flash('success','Founisè a ajoute.');}redirect('suppliers.php');}
 if($action==='delete'){$id=(int)post('id');$check=$pdo->prepare('SELECT COUNT(*) FROM produit WHERE four_id=?');$check->execute([$id]);if((int)$check->fetchColumn()>0){flash('error','Ou pa ka efase founisè sa a paske gen pwodwi ki relye avè l.');}else{$pdo->prepare('DELETE FROM fournisseur WHERE fourn_id=?')->execute([$id]);log_activity('delete','supplier',$id,'Founisè efase');flash('success','Founisè a efase.');}redirect('suppliers.php');}}
$edit=null;if(isset($_GET['edit'])){$s=$pdo->prepare('SELECT * FROM fournisseur WHERE fourn_id=?');$s->execute([(int)$_GET['edit']]);$edit=$s->fetch();}$show=isset($_GET['new'])||$edit;
$list=$pdo->query('SELECT f.*,COUNT(p.id) product_count FROM fournisseur f LEFT JOIN produit p ON p.four_id=f.fourn_id GROUP BY f.fourn_id ORDER BY f.nom')->fetchAll();page_header($show?($edit?'Modifye founisè':'Ajoute founisè'):'Founisè','suppliers');
?>
<?php if($show): ?><div class="card"><form method="post" class="form-grid"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="save"><input type="hidden" name="id" value="<?=(int)($edit['fourn_id']??0)?>"><div class="field"><label>Non biznis / siyati *</label><input name="name" required autofocus value="<?=e($edit['nom']??'')?>"></div><div class="field"><label>Non moun pou kontakte</label><input name="contact" value="<?=e($edit['prenom']??'')?>"></div><div class="field"><label>Telefòn</label><input name="phone" inputmode="tel" value="<?=e($edit['num_tel']??'')?>"></div><div class="field"><label>Vil</label><input name="city" value="<?=e($edit['ville']??'')?>"></div><div class="field full"><label>Adrès</label><input name="address" value="<?=e($edit['adresse']??'')?>"></div><div class="form-footer"><a class="button" href="suppliers.php">Anile</a><button class="primary">Sove founisè a</button></div></form></div>
<?php else: ?><div class="page-actions"><p class="muted">Moun oswa konpayi ki vann ou machandiz.</p><a class="button primary" href="suppliers.php?new=1">+ Ajoute founisè</a></div><div class="card"><div class="table-wrap"><table><thead><tr><th>Founisè</th><th>Kontak</th><th>Telefòn</th><th>Vil</th><th>Pwodwi</th><th>Aksyon</th></tr></thead><tbody><?php foreach($list as $s):?><tr><td><strong><?=e($s['nom'])?></strong></td><td><?=e($s['prenom'])?:'—'?></td><td><?=e($s['num_tel'])?:'—'?></td><td><?=e($s['ville'])?:'—'?></td><td><?=(int)$s['product_count']?></td><td><div class="actions"><a class="button small" href="suppliers.php?edit=<?=(int)$s['fourn_id']?>">Modifye</a><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=(int)$s['fourn_id']?>"><button class="button small danger" data-confirm="Efase founisè sa a?">Efase</button></form></div></td></tr><?php endforeach;?><?php if(!$list):?><tr><td colspan="6" class="empty">Poko gen founisè.</td></tr><?php endif;?></tbody></table></div></div><?php endif;page_footer();?>
