<?php
require_once __DIR__.'/core/layout.php';require_auth();$pdo=db();$me=current_user();
if($_SERVER['REQUEST_METHOD']==='POST'){verify_csrf();$action=post('action');
 if($action==='save'){if(!filter_var(post('email'),FILTER_VALIDATE_EMAIL)||strlen(post('password'))<8||post('name')===''){flash('error','Mete yon non, yon imèl valab ak yon modpas 8 karaktè.');redirect('users.php?new=1');}$duplicate=$pdo->prepare('SELECT COUNT(*) FROM users WHERE user_email=?');$duplicate->execute([strtolower(post('email'))]);if($duplicate->fetchColumn()){flash('error','Imèl sa a deja itilize.');redirect('users.php?new=1');}$parts=preg_split('/\s+/',post('name'),2);try{$pdo->prepare("INSERT INTO users(user_name,user_prenom,user_email,user_pass,user_date,user_img,user_sexe,personnalite,societe,adresse,ville,etat,cod_postal,pays,num_tel) VALUES(?,?,?,?,CURDATE(),'default.png','',?,'','','','',0,'',0)")->execute([$parts[0],$parts[1]??'',strtolower(post('email')),password_hash(post('password'),PASSWORD_DEFAULT),'admin']);$id=(int)$pdo->lastInsertId();log_activity('create','user',$id,post('email'));flash('success','Kont itilizatè a kreye.');}catch(PDOException $e){flash('error','Imèl sa a deja itilize oswa li pa valab.');}redirect('users.php');}
 if($action==='delete'){$id=(int)post('id');if($id===(int)$me['user_id'])flash('error','Ou pa ka efase pwòp kont ou pandan ou konekte.');else{$pdo->prepare('DELETE FROM users WHERE user_id=?')->execute([$id]);log_activity('delete','user',$id,'Kont itilizatè efase');flash('success','Kont lan efase.');}redirect('users.php');}}
$admins=$pdo->query("SELECT user_id,user_name,user_prenom,user_email,personnalite FROM users WHERE personnalite='admin' ORDER BY user_name")->fetchAll();$show=isset($_GET['new']);page_header($show?'Ajoute itilizatè':'Itilizatè','users');
?>
<?php if($show):?><div class="card"><form method="post" class="form-grid"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="save"><div class="field"><label>Non konplè *</label><input name="name" required autofocus></div><div class="field"><label>Imèl *</label><input type="email" name="email" required></div><div class="field"><label>Modpas tanporè *</label><input type="password" name="password" minlength="8" required><small>Bay moun nan modpas sa a an prive.</small></div><div class="field"><label>Wòl</label><select name="role"><option value="admin">Administratè — tout aksè</option></select></div><div class="form-footer"><a class="button" href="users.php">Anile</a><button class="primary">Kreye kont lan</button></div></form></div>
<?php else:?><div class="page-actions"><p class="muted">Moun ki gen dwa antre nan espas jesyon an.</p><a class="button primary" href="users.php?new=1">+ Ajoute itilizatè</a></div><div class="card"><div class="table-wrap"><table><thead><tr><th>Non</th><th>Imèl</th><th>Wòl</th><th>Aksyon</th></tr></thead><tbody><?php foreach($admins as $u):?><tr><td><strong><?=e(trim($u['user_name'].' '.$u['user_prenom']))?></strong><?= (int)$u['user_id']===(int)$me['user_id']?' (ou)':''?></td><td><?=e($u['user_email'])?></td><td><span class="badge">Administratè</span></td><td><?php if((int)$u['user_id']!==(int)$me['user_id']):?><form method="post"><input type="hidden" name="csrf" value="<?=e(csrf_token())?>"><input type="hidden" name="action" value="delete"><input type="hidden" name="id" value="<?=(int)$u['user_id']?>"><button class="button small danger" data-confirm="Efase kont sa a?">Efase</button></form><?php else:?>—<?php endif;?></td></tr><?php endforeach;?></tbody></table></div></div><?php endif;page_footer();?>
